version: 1.7.0.{build}
os: Visual Studio 2019

environment:
  ASPNETCORE_ENVIRONMENT: appveyor

configuration: Release

init:
  - git config --global core.autocrlf true
  - net start MSSQL$SQL2019

dotnet_csproj:
  patch: true
  file: 'service\version.props'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

build_script:
  - ps: ./build.ps1

test_script:
  - ps: ./test.ps1

artifacts:
  - path: 'build\*.zip'
    name: Website
  - path: 'build\database\*.dacpac'
    name: Database

for:
  - branches:
      only:
        - develop
    deploy:
      - provider: SqlDatabase
        artifact: Database
        connection_string:
          secure: MrZDPoUNN3lixNAZ8Z56md0n52EpKdJlL7QFHaIb/XFpvtO3Mt3q15f4KJM0+vmTysSGiTbpA7oIHK3DVKfOwhvsb5QbeXzvOhC6qyks+pYkjq6z3LEZMKRWUzKhcqOKGAZBm7fn8LRCBGpVbT7stzIEYsk38IOIOhkY+6cMiaxwlZ/pns9mGDD5n4rbsrf+THjLCmVAmBorACs3LqTGxg==
      - provider: AzureAppServiceZipDeploy
        artifact: Website
        website: ls-usc-app-iq-stage
        username: loresoft-azure
        password:
          secure: oYie4BaAC7RU5xupBc6NWLBNtwUpkfv5IodtvafvWQ0=

  - branches:
      only:
        - master
    deploy:
      - provider: SqlDatabase
        artifact: Database
        connection_string:
          secure: MrZDPoUNN3lixNAZ8Z56md0n52EpKdJlL7QFHaIb/XFpvtO3Mt3q15f4KJM0+vmTysSGiTbpA7oIHK3DVKfOwl0/n94G58SEgVeeImVv9JMMilfn/jTgViP63gFRcSPfuF/5DK3kVhTuYIgID3C58ExBBe37zGNZgJ5bWybhTBquxtCRd5qFa9FudRfhtGm0
      - provider: AzureAppServiceZipDeploy
        artifact: Website
        website: ls-usc-app-iq-prod
        username: loresoft-azure
        password:
          secure: oYie4BaAC7RU5xupBc6NWLBNtwUpkfv5IodtvafvWQ0=
