version: 1.3.0.{build}
os: Visual Studio 2019

environment:
  ASPNETCORE_ENVIRONMENT: appveyor

configuration: Release

services:
  - mssql2017

init:
  - git config --global core.autocrlf true

dotnet_csproj:
  patch: true
  file: 'service\version.props'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

build_script:
  - ps: ./build.ps1

test: off

artifacts:
  - path: 'build\*.zip'
    name: Website
  - path: 'build\database\*.dacpac'
    name: Database

after_deploy:
  - cmd: dotnet test service\test\InstructorIQ.Core.Tests\InstructorIQ.Core.Tests.csproj