version: 1.3.0.{build}
os: Visual Studio 2019

environment:
  ASPNETCORE_ENVIRONMENT: appveyor

configuration: Release

services:
  - mssql2017

init:
  - git config --global core.autocrlf true

dotnet_csproj:
  patch: true
  file: 'service\version.props'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

build_script:
  - ps: ./build.ps1

test_script:
  - ps: ./test.ps1

artifacts:
  - path: 'build\*.zip'
    name: Website
  - path: 'build\database\*.dacpac'
    name: Database

for:
  - branches:
      only:
        - develop
    deploy:
      - provider: Environment
        name: InstructorIQ-Database-Staging
      - provider: Environment
        name: InstructorIQ-Website-Staging
  - branches:
      only:
        - master
    deploy:
      - provider: Environment
        name: InstructorIQ-Database
      - provider: Environment
        name: InstructorIQ-Website
  