version: 1.7.0.{build}
os: Visual Studio 2022

environment:
  ASPNETCORE_ENVIRONMENT: appveyor

configuration: Release

init:
  - git config --global core.autocrlf true
  - net start MSSQL$SQL2019

dotnet_csproj:
  patch: true
  file: 'service\version.props'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

build_script:
  - ps: ./build.ps1

test_script:
  - ps: ./test.ps1

artifacts:
  - path: 'build\*.zip'
    name: Website
  - path: 'build\database\*.dacpac'
    name: Database

for:
  - branches:
      only:
        - develop
    deploy:
      - provider: SqlDatabase
        artifact: Database
        connection_string:
          secure: MrZDPoUNN3lixNAZ8Z56md0n52EpKdJlL7QFHaIb/XFpvtO3Mt3q15f4KJM0+vmTysSGiTbpA7oIHK3DVKfOwhvsb5QbeXzvOhC6qyks+pYd99utft55zeo7qsttUm488DYuEjVLVd4i1boHoci2XCrqvSybzCGLopZGZi8JP+AZ8sLlQGu7Y4URCXyaNpAFR+QQBDZDl54h/NV7umWSfK6372uMtAAxm9328D18gTbYjeb5AG0daN6X33S17XY1J3Cs4WdL2WvCw9ZfOMP27G4BPoznJs6SiQBeahJA+xMo7Kye7WxOX2HDD/IcWFRyApZyNYIjk3FvUzEf8ZvwXw3fq1/QM/gKhhX3T3G786A=
      - provider: AzureAppServiceZipDeploy
        artifact: Website
        website: ls-usc-app-iq-stage
        username: loresoft-azure
        password:
          secure: oYie4BaAC7RU5xupBc6NWLBNtwUpkfv5IodtvafvWQ0=

  - branches:
      only:
        - master
    deploy:
      - provider: SqlDatabase
        artifact: Database
        connection_string:
          secure: MrZDPoUNN3lixNAZ8Z56md0n52EpKdJlL7QFHaIb/XFpvtO3Mt3q15f4KJM0+vmTysSGiTbpA7oIHK3DVKfOwl0/n94G58SEgVeeImVv9JPi7Kj/Iw3ZGiuEk7se/awPbNgqM8/+YcjcAXBXKSUQcQv00+5oaa2LHNT1BHUDxFckC6R/cAMGixlnVN7S+FvCGwlJrV6w+/Sebn/JOAo5AipF7/PUYGQKGeWX6AggFtBqLe+accEQU8EQK3cvmXJDEfeULIj9njCm9YebZNnrwfTgxLLalFExjwBYp023IqFbWhCx65b8r9ngktOTWRZIBFxAropvMTTG8tAo2QAOig==
      - provider: AzureAppServiceZipDeploy
        artifact: Website
        website: ls-usc-app-iq-prod
        username: loresoft-azure
        password:
          secure: oYie4BaAC7RU5xupBc6NWLBNtwUpkfv5IodtvafvWQ0=
