version: 1.7.0.{build}
os: Visual Studio 2022

environment:
  ASPNETCORE_ENVIRONMENT: appveyor

configuration: Release

init:
  - git config --global core.autocrlf true
  - net start MSSQL$SQL2019

dotnet_csproj:
  patch: true
  file: 'service\version.props'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

build_script:
  - ps: ./build.ps1

test_script:
  - ps: ./test.ps1

artifacts:
  - path: 'build\*.zip'
    name: Website
  - path: 'build\database\*.dacpac'
    name: Database
