CREATE TABLE [dbo].[Datasweep]
(
    [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT [DF_Datasweep_Id] DEFAULT (NEWSEQUENTIALID()),
    [Description] NVARCHAR(255) NULL,

    [Created] DATETIMEOFFSET NOT NULL CONSTRAINT [DF_Datasweep_Created] DEFAULT (SYSUTCDATETIME()),
    [CreatedBy] NVARCHAR(100) NULL CONSTRAINT [DF_Datasweep_CreatedBy] DEFAULT (SYSTEM_USER),
    [Updated] DATETIMEOFFSET NOT NULL CONSTRAINT [DF_Datasweep_Updated] DEFAULT (SYSUTCDATETIME()),
    [UpdatedBy] NVARCHAR(100) NULL CONSTRAINT [DF_Datasweep_UpdatedBy] DEFAULT (SYSTEM_USER),
    [RowVersion] ROWVERSION NOT NULL,

    CONSTRAINT [PK_Datasweep] PRIMARY KEY NONCLUSTERED ([Id] ASC),
)
