CREATE TABLE [IQ].[Group]
(
    [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT [DF_Group_Id] DEFAULT (NEWSEQUENTIALID()),

    [Name] NVARCHAR(256) NOT NULL,
    [Description] NVARCHAR(MAX) NULL,

    [Sequence] INT NOT NULL CONSTRAINT [DF_Group_Sequence] DEFAULT (0),
    [DisplayOrder] INT NOT NULL  CONSTRAINT [DF_Group_DisplayOrder] DEFAULT (0),

    [TenantId] UNIQUEIDENTIFIER NOT NULL,

    [Created] DATETIMEOFFSET NOT NULL CONSTRAINT [DF_Group_Created] DEFAULT (SYSUTCDATETIME()),
    [CreatedBy] NVARCHAR(100) NULL,
    [Updated] DATETIMEOFFSET NOT NULL CONSTRAINT [DF_Group_Updated] DEFAULT (SYSUTCDATETIME()),
    [UpdatedBy] NVARCHAR(100) NULL,
    [RowVersion] ROWVERSION NOT NULL,

    CONSTRAINT [PK_Group] PRIMARY KEY NONCLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Group_Tenant_TenantId] FOREIGN KEY ([TenantId]) REFERENCES [IQ].[Tenant]([Id]),

)

GO
CREATE INDEX [IX_Group_Name]
    ON [IQ].[Group] ([Name])

GO
CREATE INDEX [IX_Group_TenantId]
    ON [IQ].[Group] ([TenantId])
