CREATE TABLE [dbo].[Group]
(
    [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT [DF_Group_Id] DEFAULT (NEWSEQUENTIALID()),
    [Name] NVARCHAR(256) NOT NULL,
    [Description] NVARCHAR(MAX) NULL,

    [TenantId] UNIQUEIDENTIFIER NOT NULL,

    [Created] DATETIMEOFFSET NOT NULL CONSTRAINT [DF_Group_Created] DEFAULT (SYSUTCDATETIME()),
    [CreatedBy] NVARCHAR(100) NULL,
    [Updated] DATETIMEOFFSET NOT NULL CONSTRAINT [DF_Group_Updated] DEFAULT (SYSUTCDATETIME()),
    [UpdatedBy] NVARCHAR(100) NULL,
    [RowVersion] ROWVERSION NOT NULL,

    CONSTRAINT [PK_Group] PRIMARY KEY NONCLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Group_Tenant_TenantId] FOREIGN KEY ([TenantId]) REFERENCES [Tenant]([Id]),

)

GO
CREATE INDEX [IX_Group_Name]
ON [dbo].[Group] ([Name])

GO
CREATE INDEX [IX_Group_TenantId]
ON [dbo].[Group] ([TenantId])
