CREATE TABLE [IQ].[HistoryJob]
(
    [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT [DF_HistoryJob_Id] DEFAULT (NEWSEQUENTIALID()),

	[EntityType] NVARCHAR(256) NOT NULL,
	[LastProcessDate] DATETIME2 NOT NULL,

	CONSTRAINT [PK_HistoryJob] PRIMARY KEY NONCLUSTERED ([Id] ASC),
)

GO
CREATE UNIQUE NONCLUSTERED INDEX [UX_HistoryJob_EntityType]
    ON [IQ].[HistoryJob]([EntityType] ASC);
