CREATE TABLE [IQ].[Notification]
(
    [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT [DF_Notification_Id] DEFAULT (NEWSEQUENTIALID()),

    [Type] NVARCHAR(256) NOT NULL,
    [Message] NVARCHAR(MAX) NULL,

    [CorrelationType] NVARCHAR(256) NULL,
    [CorrelationId] UNIQUEIDENTIFIER NULL,

    [Created] DATETIMEOFFSET NOT NULL CONSTRAINT [DF_Notification_Created] DEFAULT (SYSUTCDATETIME()),
    [CreatedBy] NVARCHAR(100) NULL,
    [Updated] DATETIMEOFFSET NOT NULL CONSTRAINT [DF_Notification_Updated] DEFAULT (SYSUTCDATETIME()),
    [UpdatedBy] NVARCHAR(100) NULL,
    [RowVersion] ROWVERSION NOT NULL,

    CONSTRAINT [PK_Notification] PRIMARY KEY NONCLUSTERED ([Id] ASC),
)

