CREATE TABLE [IQ].[SignUp]
(
    [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT [DF_SignUp_Id] DEFAULT (NEWSEQUENTIALID()),

    [Name] NVARCHAR(100) NOT NULL,
    [Description] NVARCHAR(MAX) NULL,

    [TenantId] UNIQUEIDENTIFIER NOT NULL,

    [Created] DATETIMEOFFSET NOT NULL CONSTRAINT [DF_SignUp_Created] DEFAULT (SYSUTCDATETIME()),
    [CreatedBy] NVARCHAR(100) NULL,
    [Updated] DATETIMEOFFSET NOT NULL CONSTRAINT [DF_SignUp_Updated] DEFAULT (SYSUTCDATETIME()),
    [UpdatedBy] NVARCHAR(100) NULL,
    [RowVersion] ROWVERSION NOT NULL,

    CONSTRAINT [PK_SignUp] PRIMARY KEY NONCLUSTERED ([Id] ASC),
    CONSTRAINT [FK_SignUp_Tenant_TenantId] FOREIGN KEY ([TenantId]) REFERENCES [IQ].[Tenant]([Id]),
)

GO
CREATE INDEX [IX_SignUp_TenantId]
ON [IQ].[SignUp] ([TenantId])
