CREATE TABLE [IQ].[Template]
(
    [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT [DF_Template_Id] DEFAULT (NEWSEQUENTIALID()),
    [Name] NVARCHAR(100) NOT NULL,
    [Description] NVARCHAR(255) NULL,

    [TemplateBody] NVARCHAR(MAX) NULL,
    [TemplateType] NVARCHAR(100) NOT NULL,

    [TenantId] UNIQUEIDENTIFIER NOT NULL,

    [Created] DATETIMEOFFSET NOT NULL CONSTRAINT [DF_Template_Created] DEFAULT (SYSUTCDATETIME()),
    [CreatedBy] NVARCHAR(100) NULL,
    [Updated] DATETIMEOFFSET NOT NULL CONSTRAINT [DF_Template_Updated] DEFAULT (SYSUTCDATETIME()),
    [UpdatedBy] NVARCHAR(100) NULL,
    [RowVersion] ROWVERSION NOT NULL,

    [PeriodStart] DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL CONSTRAINT [DF_Template_PeriodStart] DEFAULT (SYSUTCDATETIME()),
    [PeriodEnd] DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL CONSTRAINT [DF_Template_PeriodEnd] DEFAULT ('9999-12-31 23:59:59.9999999'), 
    PERIOD FOR SYSTEM_TIME ([PeriodStart], [PeriodEnd]),

    CONSTRAINT [PK_Template] PRIMARY KEY NONCLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Template_Tenant_TenantId] FOREIGN KEY ([TenantId]) REFERENCES [IQ].[Tenant]([Id]),
)
WITH 
(
    SYSTEM_VERSIONING = ON 
    (
        HISTORY_TABLE = [History].[Template],
        HISTORY_RETENTION_PERIOD = 1 YEARS,
        DATA_CONSISTENCY_CHECK = ON
    )
);

GO
CREATE INDEX [IX_Template_Name]
ON [IQ].[Template] ([Name])

GO
CREATE INDEX [IX_Template_TemplateType]
ON [IQ].[Template] ([TemplateType])

GO
CREATE INDEX [IX_Template_TenantId]
ON [IQ].[Template] ([TenantId])

