<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <NoWarn>1591</NoWarn>
    <LangVersion>latest</LangVersion>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Templates\*.yml" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Templates\*.yml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AngleSharp" Version="1.1.2" />
    <PackageReference Include="Azure.Data.Tables" Version="12.9.1" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.22.2" />
    <PackageReference Include="CsvHelper" Version="33.0.1" />
    <PackageReference Include="FluentCommand.SqlServer" Version="12.13.2" />
    <PackageReference Include="Handlebars.Net" Version="2.1.6" />
    <PackageReference Include="MediatR.CommandQuery.Audit" Version="15.9.8" />
    <PackageReference Include="MediatR.CommandQuery.EntityFrameworkCore" Version="15.9.8" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.10" />
    <PackageReference Include="NaturalSort.Extension" Version="4.3.0" />
    <PackageReference Include="SendGrid.Extensions.DependencyInjection" Version="1.0.1" />
    <PackageReference Include="UAParser" Version="3.1.47" />
    <PackageReference Include="YamlDotNet" Version="16.2.0" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Domain\EmailDelivery\Queries\" />
  </ItemGroup>

</Project>