###
GET https://localhost:5001/api/event/BF3DA08C-2C3E-E911-AA75-5CF3708FF0FB/?start=2019-04-01T00:00:00Z&end=2019-04-30T00:00:00Z

###
GET https://localhost:5001/api/event/ical/edenprairie/

###
GET https://localhost:5001/api/event/ical/edenprairie?start=2019-05-01T00:00:00Z&end=2019-07-01T00:00:00Z

###
GET https://instructoriq.com/api/event/ical/edenprairie?start=2019-05-01T00:00:00Z&end=2019-07-01T00:00:00Z

###
GET https://instructoriq.com/api/event/bf3da08c-2c3e-e911-aa75-5cf3708ff0fb/?start=2019-05-01T00%3A00%3A00-05%3A00&end=2019-06-01T00%3A00%3A00-05%3A00


###

GET https://secure4.aladtec.com/edenprairie/index.php?action=get_ical&utc=1&rid=25834&opts=st&mid=10610:89:89:3900


###

GET https://secure4.aladtec.com/edenprairie/index.php?action=get_ical&utc=1&rid=25834&opts=st&mid=10610:89:89:3900

###
GET https://calendar.google.com/calendar/embed?showNav=0&amp;showPrint=0&amp;showTz=0&amp;height=400&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=epfdtraining%40gmail.com&amp;color=%2329527A&amp;ctz=America%2FChicago

###
GET https://instructoriq.com/EdenPrairie/calendar/embed


###
GET https://localhost:5001/EdenPrairie/calendar/embed