# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - ls-usc-app-iq-stage

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Build Solution
        run: dotnet restore ./service/InstructorIQ.sln

      - name: Build Solution
        run: dotnet build ./service/InstructorIQ.sln --no-restore --configuration Release

      - name: Publish Web Application
        if: success()
        run: dotnet publish ./service/src/InstructorIQ.WebApplication/InstructorIQ.WebApplication.csproj --no-build --configuration Release --output publish/WebApplication

      - name: Publish Job Runner
        if: success()
        run: dotnet publish ./service/src/InstructorIQ.JobRunner/InstructorIQ.JobRunner.csproj --no-build --configuration Release --output publish/JobRunner

      - name: Build Database
        run: msbuild ./database/InstructorIQ.sln /t:Build /p:Configuration=Release  /p:OutputPath=publish/database

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: application
          path: publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Staging'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: application

      - name: Deploy Web Application to Azure
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ls-usc-app-iq-stage'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A55215C074554B6E86332273D364C877 }}
          package: ./WebApplication
