# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - ls-usc-app-iq-stage

env:
  BUILD_PATH: '${{github.workspace}}/publish'
  BUILD_VERSION: '1.7.${{github.run_number}}'
  BUILD_INFORMATION: '1.7.${{github.run_number}}+Branch.${{github.ref}}.Sha.${{github.sha}}'

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Output Environment 
        run: |
          echo "Workspace: ${{github.workspace}}"
          echo "Run ID: ${{github.run_id}}"
          echo "Run Number: ${{github.run_number}}"
          echo "Event: ${{github.event_name}}"
          echo "Branch: ${{github.ref}}"
          echo "Branch Name: ${{github.ref_name}}"
          echo "Hash: ${{github.sha}}"
          echo "Build Path: ${{env.BUILD_PATH}}"
          echo "Build Version: ${{env.BUILD_VERSION}}"
          echo "Build Information: ${{env.BUILD_INFORMATION}}"

      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Restore Dependencies
        run: dotnet restore ./service/InstructorIQ.sln

      - name: Build Solution
        run: 'dotnet build ./service/InstructorIQ.sln --no-restore --configuration Release -p:Version="${{env.BUILD_VERSION}}" -p:InformationalVersion="${{env.BUILD_INFORMATION}}"'

      - name: Publish Web Application
        if: success()
        run: 'dotnet publish ./service/src/InstructorIQ.WebApplication/InstructorIQ.WebApplication.csproj --no-build --configuration Release --output "${{env.BUILD_PATH}}/WebApplication"'

      - name: Publish Job Runner
        if: success()
        run: 'dotnet publish ./service/src/InstructorIQ.JobRunner/InstructorIQ.JobRunner.csproj --no-build --configuration Release --output "${{env.BUILD_PATH}}/WebApplication/App_Data/jobs/continuous/runner"'

      - name: Build Database
        if: success()
        run: 'msbuild ./database/InstructorIQ.sln /t:Build /p:Configuration=Release /p:OutputPath="${{env.BUILD_PATH}}/database"'

      - name: Upload Artifact
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: application
          path: '${{env.BUILD_PATH}}'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Staging'
      url: '${{steps.deploy-to-webapp.outputs.webapp-url}}'

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: application

      - name: Deploy Web Application to Azure
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ls-usc-app-iq-stage'
          slot-name: 'Production'
          publish-profile: ${{secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A55215C074554B6E86332273D364C877}}
          package: ./WebApplication
